spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product_catalog
    username: test
    password: test
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.r2dbc.connection.init: DEBUG

server:
  port: 8080
